import { Location } from "src/app/models/location";

export const City: Location[] = [
  
  { name: "Alice" },
  { name: "Bellville" },
  { name: "Bethlehem" },
  { name: "Benoni" },
  { name: "Bloemfontein" },
  { name: "Butterworth" },
  { name: "Boksburg" },
  { name: "Brakpan" },
  { name: "Carletonville" },
  { name: "Cape Town" },
  { name: "Constantia" },
  { name: "Durban" },
  { name: "East London" },
  { name: "Empangeni" },
  { name: "Graaff-Reinet" },
  { name: "Johannesburg" },
  { name: "Germiston" },
  { name: "Grahamstown" },
  { name: "Emalahleni" },
  { name: "Giyani" },
  { name: "George" },
  { name: "Hopefield" },
  { name: "Jagersfontein" },
  { name: "Krugersdorp" },
  { name: "King William’s Town" },
  { name: "Kroonstad" },
  { name: "Klerksdorp" },
  { name: "Kimberley" },
  { name: "Kuruman" },

  { name: "Ladysmith" },
  { name: "Lebowakgomo" },
  { name: "Mthatha" },
  { name: "Mahikeng" },
  { name: "Mmabatho" },
  { name: "Nelspruit" },
  { name: "Newcastle" },
  { name: "Odendaalsrus" },
  { name: "Parys" },
  { name: "Paarl" },
  { name: "Port Nolloth" },
  { name: "Musina" },
  { name: "Phalaborwa" },
  { name: "Polokwane" },
  { name: "Potchefstroom" },
  { name: "Pietermaritzburg" },
  { name: "Pinetown" },
  { name: "Port Elizabeth" },
  { name: "Pretoria" },
  { name: "Randburg" },
  { name: "Randfontein" },
  { name: "Roodepoort" },
  { name: "Phuthaditjhaba" },
  { name: "Seshego" },
  { name: "Sibasa" },
  { name: "Simon’s Town" },
  { name: "Stellenbosch" },
  { name: "Swellendam" },
  { name: "Secunda" },
  { name: "Soweto" },
  { name: "Springs" },
  { name: "Sasolburg" },
  { name: "Virginia" },
  { name: "Thabazimbi" },
  { name: "Oudtshoorn" },
  { name: "Queenstown" },
  { name: "Uitenhage" },
  { name: "Ulundi" },
  { name: "Umlazi" },
  { name: "Vanderbijlpark" },
  { name: "Vereeniging" },
  { name: "Worcester" },
  { name: "Welkom" },
  { name: "Zwelitsha" },
];

City.sort();
